### ISSUE TITLE
Update section 4

### ISSUE THREAD

**Issue by jhaas-pfrc** [bgp/draft-ietf-idr-bgp-sendholdtimer#11]
Text in section 4:
`If a system does not send successive KEEPALIVE or UPDATE messages within the period specified in SendHoldTime, then a NOTIFICATION message with the "Send Hold Timer Expired" Error Code MAY be sent and the BGP connection MUST be closed.`

The text was updated in the prior section to talk about all messages.

**Comment by job** [comment]
Fixed via https://github.com/bgp/draft-ietf-idr-bgp-sendholdtimer/pull/13
