### ISSUE TITLE
IANA considerations

### ISSUE THREAD

**Issue by jhaas-pfrc** [bgp/draft-ietf-idr-bgp-sendholdtimer#12]
`IANA has registered code 8 for "Send Hold Timer Expired" in the "BGP Error (Notification) Codes" sub-registry under the "Border Gateway Protocol (BGP) Parameters" registry.`

This is the definition of the new error code section.  The protocol requires subcodes as well for notifications.

The fix is to ask for a registry for the subcodes and place a single entry in it, "0" for RESERVED to say that there is nothing.

You should also update the text to indicate that there is no error data expected in this notification message code/subcode.

**Comment by job** [comment]
Why is a sub sub registry required? Doesn't `HoldTimer_Expired` close without sub code? https://www.rfc-editor.org/rfc/rfc4271.html#section-6.5

**Comment by jhaas-pfrc** [comment]
Ok, that's the document hint I needed to avoid the sub registry.  Just note you send error subcode 0/unspecific.

Thanks.
